AWSTemplateFormatVersion: "2010-09-09"
Description: Create a role for us to assume and create a resource we'll have access to
Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
  StsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/sts-machine-user"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource:
                  - !GetAtt Bucket.Arn
                  - !Sub "${Bucket.Arn}/*"
Outputs:
  RoleArn:
    Value: !GetAtt StsRole.Arn
  BucketName:
    Value: !Ref Bucket