AWSTemplateFormatVersion: "2010-09-09"
Description: Launch a functional EC2 Web Server for testing VPCs

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
  VpcID:
    Type: String
    Default: vpc-072b8edab238ba34b
  ImageID:
    Type: String
    Default: ami-0d18d736c0fb6e4fe
  SubnetId:
    Type: String
    Default: subnet-025691ea63e9d1aa4

Resources:
  MyEC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2SSMRole-Testing-Server
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MyEC2Role

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageID
      IamInstanceProfile: !Ref MyInstanceProfile
      NetworkInterfaces:
        - DeviceIndex: "0"
          AssociatePublicIpAddress: true
          SubnetId: !Ref SubnetId
          GroupSet:
            - !GetAtt SG.GroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Success! The server is running inside your testing VPC.</h1>" > /var/www/html/index.html

  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and test traffic to client host
      VpcId: !Ref VpcID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
