#!/usr/bin/env bash
echo "==sync"
set -e
# Check for bucket name
if [ -z "$1" ]; then 
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Check for filename prefix
if [ -z "$1" ]; then 
    echo "There needs to be a fileprefix eg. ./bucket my-fileprefix-name"
    exit 1
fi
BUCKET_NAME=$1
FILENAME_PREFIX=$2

OUTPUT_DIR=/tmp/s3-bash-scripts

# remove file if already exists
rm -rf $OUTPUT_DIR

# let create output folder
mkdir -p "$OUTPUT_DIR"

# Generate a random number of files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++))
do
    FILENAME=$OUTPUT_DIR/${FILENAME_PREFIX}$i.txt
    
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree "$OUTPUT_DIR"

aws s3 sync "$OUTPUT_DIR" "s3://$BUCKET_NAME/"